config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_for :admins,skip: [:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }

  scope module: :user do
    get root to: "recipes#index"
    resources :users, only: [:index,:show,:edit,:update]
    resources :recipes do
      resource :favorites,only: [:create,:destroy]
    end
    get 'daily_recipes'=>"recipes#daily_recipes",as: "daily_recipes"
    get 'search'=>'recipes#searches',as: 'search'
    resources :events do
      collection do
        delete :destroy_all
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord

# gem:acts_as_taggableの使用
   acts_as_taggable_on :tags

   validates :title,presence: true
   validates :introduction,presence: true

   belongs_to :user
   has_many :favorites,dependent: :destroy
   has_many :steps,dependent: :destroy
   has_many :ingredients,dependent: :destroy
#   子モデルのカラムを許可
   accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
   accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank

   has_one_attached :image

    def get_image(width, height)
      if image.attached?
        # サイズ変更と画像の中央に表示場所を設定
        image.variant(resize: "#{width}x#{height}^", gravity: 'center', crop: "#{width}x#{height}+0+0").processed
      else
        "no_image"
      end
    end

    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end

    def self.looks(word)
      @recipe = Recipe.where("title LIKE?","%#{word}%").distinct
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :recipes,dependent: :destroy
         has_many :favorites,dependent: :destroy

         has_one_attached :profile_image

         validates :name,presence: true
         validates :introduction,length: { maximum: 200 }

        # サイズ変更
        def get_profile_image(width, height)
          if profile_image.attached?
            profile_image.variant(resize: "#{width}x#{height}^", gravity: 'center', crop: "#{width}x#{height}+0+0").processed
          else
            "no_image"
          end
        end

end

app/controllers/concerns/users.rb
# 正しい例
module Users
    extend ActiveSupport::Concern

    included do
      before_action :get_users,only: [:index]
    end

    def get_users
        @users = User.all
    end

end

# 悪い例
# module Users
#     extend ActiveSupport::Concern

#     included do
#       before_action :get_users,only: [:index]
#       def get_users
#         @users = User.all
#       end
#     end
# end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController

  def create
    @event = Event.new(event_params)
    if @event.save
    redirect_to events_path
    else
      @events = Event.all
      render :index
      @event = Event.new
    end
  end

  def index
    @event = Event.new
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy_all
    Event.destroy_all
    redirect_to request.referer
  end

  private

  def event_params
    params.require(:event).permit(:title,:cooking_number,:amount)
  end

end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.new(recipe_id: @recipe.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
    @favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/recipes_controller.rb
class User::RecipesController < ApplicationController
 before_action :authenticate_user!,only: [:create,:edit,:new,:update,:destroy]

 def new
   @recipe = Recipe.new
 end

 def create
  @recipe = Recipe.new(recipe_params)
  @recipe.user_id = current_user.id
  if @recipe.save
    flash[:notice] = "レシピを登録しました"
    redirect_to recipe_path(@recipe)
  else
    flash.now[:alert] = "レシピの登録に失敗しました"
    render :new
  end
 end

 def index
  @recipes = Recipe.page(params[:page]).per(5)
 end

 def edit
  @recipe = Recipe.find(params[:id])
 end

 def update
  @recipe = Recipe.find(params[:id])
  if @recipe.update(recipe_params)
   flash[:notice] = "レシピを更新しました"
   redirect_to recipe_path(@recipe)
  else
   flash[:alert] = "レシピの更新に失敗しました"
   render :edit
  end
 end

 def show
  @recipe = Recipe.find(params[:id])
 end

 def destroy
  @recipe = Recipe.find(params[:id])
  @recipe.destroy
  flash[:notice] = "レシピを削除しました"
  redirect_to recipes_path
 end

 # その日ごとのレシピを取得
 def daily_recipes
   @date = Date.parse(params[:date])
   @recipes = daily_recipes_for_date(@date)
 end

 def searches
  @range = params[:range]
  @word = params[:word]

  if @range == "料理名"
   @recipes = Recipe.looks(params[:word])
  elsif @range == "材料"
   @ingredients = Ingredient.looks(params[:word])
  else
   @recipes = Recipe.all
  end
 end

 private

 def recipe_params
  # 子要素のカラムの許可
  params.require(:recipe).permit(:title,:introduction,:image,:favorite, ingredients_attributes: [:id, :name, :quantity, :_destroy],steps_attributes: [:id,:text,:cook_image,:_destroy])
 end

 def daily_recipes_for_date(date)
   Recipe.where(created_at: date.beginning_of_day..date.end_of_day)
 end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  # users/concernに定義
  include Users

  # users/concernに定義
  def index
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
    @favorite_recipes = Recipe.where(user: @user, favorite: true)
    favorites = Favorite.where(user_id: @user.id).pluck(:recipe_id)
    # いいねした投稿一覧
    @like_recipes = Recipe.where(id: favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "情報の更新に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/recipes_helper.rb
module User::RecipesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
  
  def recipe_user?(user)
     @recipe.user == current_user
  end
  
end

app/views/user/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.label :name, "材料名" %>
  <%= f.text_field :name %>

  <%= f.label :quantity, "用量",class: "ml-5 mb-3" %>
  <%= f.text_field :quantity %>

  <%= link_to_remove_association "削除", f,class: "btn btn-danger" %>
</div>

app/views/user/recipes/_searches.html.erb
<div class="search_form">
  <%= form_with url: search_path,method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['料理名'],['材料']]) %>
    <%= f.submit "検索",class: "btn btn-primary" %>
  <% end %>
</div>

app/views/user/recipes/_step_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2 class="counter"></h2>
      <div class="form-group">
        <%= f.file_field :cook_image,accept: "image/*" %>
      </div>
      <div class="form-group">
        <%= f.label :text, "手順" %>
        <%= f.text_area :text,rows: 2,class: "introduction mx-auto", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= link_to_remove_association "削除", f,class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/user/recipes/daily_recipes.html.erb
<h2 class="text-center title"><%= @date.strftime("%Y年%m月%d日") %>に投稿されたレシピ</h2>

<table class="table">
  <% @recipes.each do |recipe| %>
    <tr>
      <td>
        <%= link_to recipe_path(recipe.id) do %>
        <%= image_tag recipe.get_image(100,100) %>
        <% end %>
      </td>
      <td><%= link_to recipe.title,recipe_path(recipe.id) %></td>
      <td>
        <%= link_to user_path(recipe.user_id) do %>
        <%= image_tag recipe.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td><%= link_to recipe.user.name,user_path(recipe.user_id) %></td>
    </tr>
  <% end %>
</table>

app/views/user/recipes/edit.html.erb
<div class="row">
  <div class="col-12 mx-auto text-center">
    <h3 class="title"><%= @recipe.title %>の編集</h3>

    <div class="under">
      <p>レシピを編集します。</p>
      <p>食材、用量、調理手順を入力し[更新]をクリックしてください。</p>
      <p>お気に入り登録をしたい場合は[お気に入り登録]をクリックしてください</p>
    </div>

    <%= form_with model: @recipe do |f| %>

      <div>
        <%= f.file_field :image,accept: "image/*" %>
      </div>

      <div>
        <%= f.label :introduction,"料理紹介",class: "title2 mt-5", style: "font-size: 20px;" %>
        <%= f.text_area :introduction,rows: 3,class: "introduction form-control mx-auto mb-5" %>
      </div>

      <div>
        <%= f.label :title, "レシピ名" %>
        <%= f.text_field :title %>
      </div>

      <div id="ingredients">
        <%= link_to_add_association '材料の追加', f, :ingredients,
          data: { association_insertion_method: 'append'}, class: "btn btn-primary my-3" %>
        <%= f.fields_for :ingredients do |i| %>
          <div class="nested-fields">
            <%= i.label :name, "材料名" %>
            <%= i.text_field :name %>

            <%= i.label :quantity, "用量",class: "ml-5 mb-3" %>
            <%= i.text_field :quantity %>

            <%= link_to_remove_association "削除", i,class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>

      <div id="steps">
       <%= link_to_add_association '手順の追加', f, :steps,
         data: { association_insertion_method: 'append' }, class: "btn btn-primary my-3" %>
       <%= f.fields_for :steps do |s| %>
        <div class="nested-fields">

          <%= s.label :text, "手順",class: "ml-5 mb-3" %>
          <%= s.text_area :text,rows: 2, class: "form-control introduction mx-auto" %>

          <%= link_to_remove_association "削除", s,class: "btn btn-danger" %>
        </div>
       <% end %>
      </div>
      <div class="field">
        <%= f.label :favorite, "自信作に登録" %><br>
        <%= f.radio_button :favorite, true,style: 'transform: scale(1.5);' %>
        <%= f.label :favorite, 'する' %>

        <%= f.radio_button :favorite, false,style: 'transform: scale(1.5);',class: "ml-5" %>
        <%= f.label :favorite, 'しない' %>
      </div>
      <%= f.submit "更新",class: "my-5" %>
    <% end %>

  </div>
</div>

app/views/user/recipes/index.html.erb
<div class="text-center">
  <h2 class="title test1">CookPlanへようこそ！</h2>

  <div class="about mx-auto">
    <p>楽しく料理して共有しませんか？</p>
    <p>材料の意外な使い方が見つかるかも？</p>
  </div>
</div>

<table class="table table-hover">
  <% @recipes.each do |recipe| %>
    <tr>
      <td>
        <%= link_to recipe_path(recipe.id) do %>
          <%= image_tag recipe.get_image(100,100) %>
        <% end %>
      </td>
      <td><%= link_to recipe.title,recipe_path(recipe.id) %></td>
      <td>お気に入り数<%= recipe.favorites.count %>件</td>
    </tr>
  <% end %>
  <%= paginate @recipes %>
</table>

<h2 class="about mx-auto text-center">
  日替わりで探す
</h2>
<div class="text-center">
  <%= month_calendar do |date| %>
    <%= date.day %>
    <br>
    <!--投稿数が0のものはリンクにしない-->
    <% unless Recipe.where(created_at: date.beginning_of_day..date.end_of_day).count == 0 %>
      <%= link_to daily_recipes_path(date: date) do %>
      <!--作成日がその日の始まりから終わりまでの範囲のデータを取得-->
      投稿件数: <%= Recipe.where(created_at: date.beginning_of_day..date.end_of_day).count %>
      <% end %>
    <% else %>
      投稿件数: <%= Recipe.where(created_at: date.beginning_of_day..date.end_of_day).count %>
    <% end %>
  <% end %>
</div>

app/views/user/recipes/new.html.erb
<div class="row">
  <div class="col-12 mx-auto text-center">
    <h3 class="title">新規登録</h3>

    <div class="under">
      <p>レシピを登録します。</p>
      <p>食材、用量、調理手順を入力し[新規登録]をクリックしてください。</p>
      <p>食材や調理手順を追加したい場合は[食材を追加]、[手順を追加]をクリックしてください。</p>
    </div>

    <% if @recipe.errors.any? %>
      <%= @recipe.errors.count %>件のエラーが発生しました
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>

    <%= form_with model: @recipe do |f| %>

      <div>
        <%= f.file_field :image,accept: "image/*" %>
      </div>

      <div>
        <%= f.label :introduction,"料理紹介",class: "title2 mt-5", style: "font-size: 20px;" %>
        <%= f.text_area :introduction,rows: 3,class: "introduction form-control mx-auto mb-5" %>
      </div>

      <div>
        <%= f.label :title, "レシピ名" %>
        <%= f.text_field :title %>
      </div>

      <div id="ingredients">
        <%= link_to_add_association '材料の追加', f, :ingredients,
          data: { association_insertion_method: 'append'}, class: "btn btn-primary my-3" %>
        <%= f.fields_for :ingredients do |i| %>
          <div class="nested-fields">
            <%= i.label :name, "材料名" %>
            <%= i.text_field :name %>

            <%= i.label :quantity, "用量",class: "ml-5 mb-3" %>
            <%= i.text_field :quantity %>

            <%= link_to_remove_association "削除", i,class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>

      <div id="steps">
       <%= link_to_add_association '手順の追加', f, :steps,
         data: { association_insertion_method: 'append' }, class: "btn btn-primary my-3" %>
       <%= f.fields_for :steps do |s| %>
          <div class="nested-fields">

            <%= s.label :text, "手順",class: "ml-5 mb-3" %>
            <%= s.text_field :text %>

            <%= link_to_remove_association "削除", s,class: "btn btn-danger" %>
          </div>
       <% end %>
      </div>

      <%= f.submit "作成する",class: "my-5" %>
    <% end %>

  </div>
</div>

app/views/user/recipes/searches.html.erb
<table class="table">
  <% if @range == "料理名" %>
    <h3>「<%= @word %>」を含む料理名</h3>
    <% @recipes.each do |recipe| %>
      <tr>
        <td>
          <%= link_to recipe_path(recipe.id) do %>
            <%= image_tag recipe.get_image(100,100) %>
          <% end %>
        </td>
        <td><%= link_to recipe.title,recipe_path(recipe.id) %></td>
      </tr>
    <% end %>
  <% else %>
    <h3>材料「<%= @word %>」を含むレシピ</h3>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td>
          <%= link_to recipe_path(ingredient.recipe.id) do %>
            <%= image_tag ingredient.recipe.get_image(100,100) %>
          <% end %>
          </td>
        <td><%= link_to ingredient.recipe.title,recipe_path(ingredient.recipe.id) %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/user/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <div class="text-center">
        <%= image_tag @recipe.get_image(200,200) %>
      </div>

      <h3 class="title text-center">
        <%= @recipe.title %>
        <% if user_signed_in? %>
          <% if @recipe.user == current_user %>
            <%= link_to "レシピを編集",edit_recipe_path(@recipe),class: "btn btn-secondary" %>
          <% else %>
            <% if @recipe.favorited_by?(current_user) %>
              <%= link_to "お気に入り解除",recipe_favorites_path(@recipe),method: :delete,class: "btn btn-danger" %>
            <% else %>
              <%= link_to "お気に入り登録",recipe_favorites_path(@recipe),method: :post,class: "btn btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
      </h3>

      <div class="text-right mb-3">
        作成者:<%= link_to @recipe.user.name,user_path(@recipe.user) %>
        <%= image_tag @recipe.user.get_profile_image(100,100) %>
      </div>
      <div class="introduction2-container">
        <div class="title3 mx-auto mb-5 text-center">
          <%= @recipe.introduction %>
        </div>
      </div>

      <table class="table">
        <tr>
          <th>材料</th>
          <th style="text-align: right;">用量</th>
        </tr>
      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.name %></td>
          <td style="text-align: right;"><%= ingredient.quantity %></td>
        </tr>
      <% end %>
      </table>

      <h3 class="title3 mx-auto my-5 text-center">
        料理手順
      </h3>
      <table class="table">
        <% @recipe.steps.each_with_index do |step,index| %>
        <tr>
          <td>
            <span style="color: red; font-weight: bold;"><%= index + 1 %></span>：<%= step.text %>
          </td>
          <td>
            <%= image_tag step.get_cook_image(100,100) %>
          </td>
        </tr>
        <% end %>
      </table>

      <!--users_helperに定義-->
      <% if recipe_user?(current_user) %>
        <%= link_to "削除する",recipe_path(@recipe),method: :delete,"data-confirm"=>"レシピを削除しますか？",class: "btn btn-danger" %>
      <% end %>

    </div>
  </div>
</div>