config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_for :admins,skip: [:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }

  scope module: :user do
    get root to: "recipes#index"
    resources :users, only: [:index,:show,:edit,:update]
    resources :recipes do
      resource :favorites,only: [:create,:destroy]
    end
    get 'daily_recipes'=>"recipes#daily_recipes",as: "daily_recipes"
    get 'search'=>'recipes#searches',as: 'search'
    resources :events do
      collection do
        delete :destroy_all
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true

  enum cooking_number: { japan: 0, usa: 1, china: 2,korea: 3}

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  # user_idとrecipe_idの組み合わせに一意性
  validates :user_id,uniqueness: {scope: :recipe_id}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  def self.looks(word)
    @ingredient = Ingredient.where("name LIKE?","%#{word}%")
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord

# gem:acts_as_taggableの使用
   acts_as_taggable_on :tags

   validates :title,presence: true
   validates :introduction,presence: true

   belongs_to :user
   has_many :favorites,dependent: :destroy
   has_many :steps,dependent: :destroy
   has_many :ingredients,dependent: :destroy
#   子モデルのカラムを許可
   accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
   accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank

   has_one_attached :image

    def get_image(width, height)
      if image.attached?
        # サイズ変更と画像の中央に表示場所を設定
        image.variant(resize: "#{width}x#{height}^", gravity: 'center', crop: "#{width}x#{height}+0+0").processed
      else
        "no_image"
      end
    end

    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end

    def self.looks(word)
      @recipe = Recipe.where("title LIKE?","%#{word}%").distinct
    end

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe

  has_one_attached :cook_image

    def get_cook_image(width, height)
      if cook_image.attached?
        cook_image.variant(resize: "#{width}x#{height}^", gravity: 'center', crop: "#{width}x#{height}+0+0").processed
      else
        "no_image"
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :recipes,dependent: :destroy
         has_many :favorites,dependent: :destroy

         has_one_attached :profile_image

         validates :name,presence: true
         validates :introduction,length: { maximum: 200 }

        # サイズ変更
        def get_profile_image(width, height)
          if profile_image.attached?
            profile_image.variant(resize: "#{width}x#{height}^", gravity: 'center', crop: "#{width}x#{height}+0+0").processed
          else
            "no_image"
          end
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/users.rb
# 正しい例
module Users
    extend ActiveSupport::Concern

    included do
      before_action :get_users,only: [:index]
    end

    def get_users
        @users = User.all
    end

end

# 悪い例
# module Users
#     extend ActiveSupport::Concern

#     included do
#       before_action :get_users,only: [:index]
#       def get_users
#         @users = User.all
#       end
#     end
# end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController

  def create
    @event = Event.new(event_params)
    if @event.save
    redirect_to events_path
    else
      @events = Event.all
      render :index
      @event = Event.new
    end
  end

  def index
    @event = Event.new
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy_all
    Event.destroy_all
    redirect_to request.referer
  end

  private

  def event_params
    params.require(:event).permit(:title,:cooking_number,:amount)
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/recipes_controller.rb
class User::RecipesController < ApplicationController
 before_action :authenticate_user!,only: [:create,:edit,:new,:update,:destroy]

 def new
   @recipe = Recipe.new
 end

 def create
  @recipe = Recipe.new(recipe_params)
  @recipe.user_id = current_user.id
  if @recipe.save
    flash[:notice] = "レシピを登録しました"
    redirect_to recipe_path(@recipe)
  else
    flash.now[:alert] = "レシピの登録に失敗しました"
    render :new
  end
 end

 def index
  @recipes = Recipe.page(params[:page]).per(5)
 end

 def edit
  @recipe = Recipe.find(params[:id])
 end

 def update
  @recipe = Recipe.find(params[:id])
  if @recipe.update(recipe_params)
   flash[:notice] = "レシピを更新しました"
   redirect_to recipe_path(@recipe)
  else
   flash[:alert] = "レシピの更新に失敗しました"
   render :edit
  end
 end

 def show
  @recipe = Recipe.find(params[:id])
 end

 def destroy
  @recipe = Recipe.find(params[:id])
  @recipe.destroy
  flash[:notice] = "レシピを削除しました"
  redirect_to recipes_path
 end

 # その日ごとのレシピを取得
 def daily_recipes
   @date = Date.parse(params[:date])
   @recipes = daily_recipes_for_date(@date)
 end

 def searches
  @range = params[:range]
  @word = params[:word]

  if @range == "料理名"
   @recipes = Recipe.looks(params[:word])
  elsif @range == "材料"
   @ingredients = Ingredient.looks(params[:word])
  else
   @recipes = Recipe.all
  end
 end

 private

 def recipe_params
  # 子要素のカラムの許可
  params.require(:recipe).permit(:title,:introduction,:image,:favorite, ingredients_attributes: [:id, :name, :quantity, :_destroy],steps_attributes: [:id,:text,:cook_image,:_destroy])
 end

 def daily_recipes_for_date(date)
   Recipe.where(created_at: date.beginning_of_day..date.end_of_day)
 end

end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  # users/concernに定義
  include Users

  # users/concernに定義
  def index
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
    @favorite_recipes = Recipe.where(user: @user, favorite: true)
    favorites = Favorite.where(user_id: @user.id).pluck(:recipe_id)
    # いいねした投稿一覧
    @like_recipes = Recipe.where(id: favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "情報の更新に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
  # 送られてきたデータを日本語で表示するためにja.ymlファイルで参照する
  def display_cooking_number(event)
    I18n.t("activerecord.attributes.event.cooking_numbers.#{event.cooking_number}")
  end
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/recipes_helper.rb
module User::RecipesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
  
  def recipe_user?(user)
     @recipe.user == current_user
  end
  
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
  <%= link_to edit_user_path(current_user) do %>
    <%= image_tag current_user.get_profile_image(250, 250), class: "rounded-circle mx-auto",style: "width: 150px; height: 150px;" %>
  <% end %>
  <h4><%= current_user.name %></h4>
  <%= link_to "マイページ",user_path(current_user),class: "mt-5 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "会員一覧",users_path,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "レシピ一覧",recipes_path,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "料理投稿",new_recipe_path,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "ログアウト",destroy_user_session_path,method: :delete,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
<% else %>
  <%= link_to "トップ",recipes_path,class: "mt-5 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "新規登録",new_user_registration_path,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
  <%= link_to "ログイン",new_user_session_path,class: "mt-1 bg-dark",style: "font-size: 25px;" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookPlan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6726daaf8d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 d-flex flex-column text-center" style="background-color: #ebe1a9;">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="col-md-10" style="background-color: #f8f4e6;">
          <% if flash[:notice] %>
            <div class="flash-notice text-center">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="flash-alert text-center">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <div class="text-center mt-3">
            <%= render 'user/recipes/searches' %>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
    <footer>

    </footer>
  </body>
</html>